# Generated by Django 5.1.7 on 2025-03-18 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('chef_antenne', models.CharField(max_length=110, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fonction', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=15, unique=True)),
                ('type', models.CharField(choices=[('ordinateur', 'Ordinateur'), ('imprimante', 'Imprimante'), ('serveur', 'Serveur'), ('autre', 'Autre')], max_length=50)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_reparation', 'En réparation'), ('hors_service', 'Hors service'), ('reserve', 'Réservé')], default='actif', max_length=50)),
                ('antenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.antenne')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.employe')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('chef', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('antenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.antenne')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_parc.service'),
        ),
        migrations.AddField(
            model_name='employe',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_parc.service'),
        ),
    ]
