# Generated by Django 5.1.7 on 2025-03-20 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_parc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historique',
            name='action',
            field=models.CharField(choices=[('ATTRIBUTION', 'Attribution'), ('RETOUR', 'Retour'), ('MAINTENANCE', 'Maintenance'), ('REPARATION', 'Réparation'), ('SUPPRESSION', 'Suppression')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historique',
            name='date_action',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
